security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^%webapp_path%/Account/Login$
            security: false

        secured_area:
            pattern:   ^%webapp_path%
            security: %security_enabled%
            form_login:
                check_path: login_check
                login_path: concerto_cms_admin_login
                username_parameter: username
                password_parameter: password
#            http_basic:
#                realm: "CMS"
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

            logout:
                path:   %webapp_path%/Account/Logout
                target: /

    providers:
        in_memory:
            memory:
                users: %security_credentials%
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: %webapp_path%/Account/Login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: %webapp_path%/Account/CheckLogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }